version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  django:
    container_name: cd_django
    build: ./
    volumes:
        - ./src:/src:rw
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      PROCESS: DEV_DJANGO

#  nginx:
#    restart: always
#    container_name: nginx
#    image: nginx:1.19.5-alpine
#    depends_on:
#      - django
#    environment:
#      - TZ=Asia/Almaty
##    volumes:
##      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - "80:80"
#      - "443:443"