name: Update env variable workflow `

on:
  workflow_dispatch:
    inputs:
      github_secret_name:
        type: string
        description: 'Variable name from Github Secrets'
        required: true

jobs:

  update_env_variable:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh rollback.sh script
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 77.243.80.50
          username: ubuntu
#          key: ${{ secrets.SSH_KEY }}
          password: E0JklNc3lwFzxdZXCmkJUx4=
          script: |
            sh update_env_variable.sh ${{ inputs.github_secret_name }}=${{ secrets[inputs.github_secret_name] }}
            exit

      - name: cleanup
        run: rm -rf ~/.ssh
