# This is a basic workflow that is manually triggered

name: Build workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      rollback_commit:
        type: string
        description: 'rollback commit'
        required: true
      django:
        type: boolean
        description: 'Django service'
        default: 'true'
      verme:
        type: boolean
        description: 'Verme service'
        default: 'false'
      vision:
        type: boolean
        description: 'Vision service'
        default: 'false'


jobs:
  build_release_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout release commit
      uses: actions/checkout@v3

#    - name: Move to working dir
#      run: cd scripts/build_and_deploy

    - name: Build and push django
      run: cd scripts/build_and_deploy && python3 build.py --tag-name=master --vision-service

  build_rollback_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rollback commit
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.rollback_commit }}

#      - name: Move to working dir
#        run: cd scripts/build_and_deployy

      - name: Build and push django
        run: cd scripts/build_and_deploy && python3 build.py --tag-name=rollback --vision-service
