name: Build workflow

on:
  workflow_dispatch:
    inputs:
      rollback_commit:
        type: string
        description: 'rollback commit'
        required: true
      django:
        type: boolean
        description: 'Django'
        default: true
      verme:
        type: boolean
        description: 'Verme'
        default: false
      vision:
        type: boolean
        description: 'Vision'
        default: false


jobs:
  build_release_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout release commit
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: kairkhan
        password: dckr_pat_cUCbTzle3Gn5ql7CpIuuh2ujQZI

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push django
      if: ${{ inputs.django }}
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/back_end:master

    - name: Build and push verme
      if: ${{ inputs.verme }}
      uses: docker/build-push-action@v4
      with:
        context: ./verme/
        file: Dockerfile
        push: true
        tags: kairkhan/verme:master

    - name: Build and push vision
      if: ${{ inputs.vision }}
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./src/vision/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/vision:master


#  build_rollback_commit:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout rollback commit
#        uses: actions/checkout@v3
#        with:
#          ref: ${{ inputs.rollback_commit }}
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USER }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Build and push django
#        if: ${{ inputs.django }}
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USER }}/back_end:rollback
#
#      - name: Build and push verme
#        if: ${{ inputs.verme }}
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: ./src/verme/Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USER }}/verme:rollback
#
#      - name: Build and push vision
#        if: ${{ inputs.vision }}
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: ./src/vision/Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USER }}/vision:rollback

