# This is a basic workflow that is manually triggered

name: Build workflow

# Controls when the action will run. Workflow runs when manually triggered using the UIs
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      rollback_commit:
        type: string
        description: 'rollback commit'
        required: true
      django:
        type: boolean
        description: 'Django'
      verme:
        type: boolean
        description: 'Verme'
      vision:
        type: boolean
        description: 'Vision'


jobs:
  build_release_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout release commit
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
#        username: ${{ secrets.DOCKERHUB_USER }}
        username: kairkhan
        password: dckr_pat_gwC3WsWgNKAZ_iQ3dUXy_4zXl9k
#        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push django
      if: ${{ inputs.django }}
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: kairkhan/back_end:master

    - name: Build and push verme
      if: ${{ inputs.verme }}
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./src/verme/Dockerfile
        push: true
        tags: kairkhan/verme:master

    - name: Build and push vision
      if: ${{ inputs.vision }}
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./src/vision/Dockerfile
        push: true
        tags: kairkhan/vision:master

    

#    - name: Build and push djangoss
#      run: cd scripts/build_and_deploy && python3 build.py --tag-name=master --vision-service

  build_rollback_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rollback commit
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.rollback_commit }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
#        username: ${{ secrets.DOCKERHUB_USER }}
          username: kairkhan
          password: dckr_pat_gwC3WsWgNKAZ_iQ3dUXy_4zXl9k
#        password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push django
        if: ${{ inputs.django == 'true' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: kairkhan/back_end:rollback

      - name: Build and push verme
        if: ${{ inputs.verme == 'true' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/verme/Dockerfile
          push: true
          tags: kairkhan/verme:rollback

      - name: Build and push vision
        if: ${{ inputs.vision == 'true' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/vision/Dockerfile
          push: true
          tags: kairkhan/vision:rollback

#      - name: Build and push djangos
#        run: cd scripts/build_and_deploy && python3 build.py --tag-name=rollback --vision-service
