name: Deploy for stage server

on:
  push:
    branches:
      - master

#incr.20.03.2023

jobs:
  git_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch tags from remote
        run: git fetch --tags
      - name: Set git tag by incr to last tag
        run: git tag $(( $(git tag | sort -V | tail -1 | cut -d "." -f 1) + 1 )).$(date +'%d.%m.%Y')
      - name: Push recently created tag to remote
        run: git push origin $(git tag | sort -V | tail -1)

  build:
    needs: git_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup latest tag as env
        run: git fetch --tags && echo "GIT_LATEST_TAG=$(git tag | sort -V | tail -1)" >> $GITHUB_ENV
      - name: Echo tag
        run: echo $GIT_LATEST_TAG

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/cd_3_jobs:${{ env.GIT_LATEST_TAG }}
            ${{ secrets.DOCKERHUB_USER }}/cd_3_jobs:latest

      - name: Get changed files in the verme folder
        id: changed-files-in-verme
        uses: tj-actions/changed-files@v35
        with:
          files: src/verme/**
      - name: Build and push verme service
        if: steps.changed-files-in-verme.outputs.any_changed == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
#          file: ./src/serviceName-1/Dockerfile
          file: ./src/verme/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/testverme:${{ env.GIT_LATEST_TAG }}
            ${{ secrets.DOCKERHUB_USER }}/testverme:latest

      - name: Get changed files in the vision folder
        id: changed-files-in-vision
        uses: tj-actions/changed-files@v35
        with:
          files: src/vision/**
      - name: Build and push service vision
        if: steps.changed-files-in-vision.outputs.any_changed == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/vision/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/testvision:${{ env.GIT_LATEST_TAG }}
            ${{ secrets.DOCKERHUB_USER }}/testvision:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: | 
            cd ${{ secrets.WORK_DIR }} 
            docker-compose -f docker-compose.prod.yml pull 
            docker-compose -f docker-compose.prod.yml down 
            docker-compose -f docker-compose.prod.yml up -d 
            exit
      - name: cleanup
        run: rm -rf ~/.ssh