name: Deploy for stage server

on:
  push:
    branches:
      - master

jobs:
  git_tag:
#    env:
#      TAG_VERSION: ${{ github.event.repository.updated_at}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set git tag
#        run: git tag ${{ env.TAG_VERSION }}
        run: git tag v4.0.1
      - name: push to remote
#        run: git push origin ${{ env.TAG_VERSION }}s
        run: git push origin v4.0.1

  build:
    needs: git_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
#          tags: ${{ secrets.DOCKERHUB_USER }}/cd_3_jobs:${{ env.TAG_VERSION }}
          tags: ${{ secrets.DOCKERHUB_USER }}/cd_3_jobs:v4.0.1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
#      - name: install ssh keys
#        run: |
#          install -m 600 -D /dev/null ~/.ssh/id_rsa
#          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
#      - name: connect to server
#        run: ssh -t -t ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}s
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: cd ${{ secrets.WORK_DIR }} && docker-compose pull && docker-compose down && docker-compose up -d && exit
      - name: cleanup
        run: rm -rf ~/.ssh