name: Docker Image CI

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and up
        run: docker-compose up -d

  migration_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: migration_check
        run: docker-compose run django python manage.py migrate --fake
