name: Deploy workflow

on:
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
#          host: ${{ secrets.SSH_HOST }}
          host: 195.210.47.93
#          username: ${{ secrets.SSH_USER }}
          username: root
#          password: ${{ secrets.SSH_PASSWORD }}
          password: test
          script: |
            sh deploy.sh
            exit

      - name: cleanup
        run: rm -rf ~/.ssh


