name: Rollback workflow

on:
  workflow_dispatch:

jobs:

  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh rollback.sh script
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
         # password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sh rollback.sh
            exit

      - name: cleanup
        run: rm -rf ~/.ssh


