name: Rollback migration workflow

on:
  workflow_dispatch:
    inputs:
      rollback_migration_app_name:
        type: string
        description: 'Rollback migration app name'
        required: true

      rollback_migration_number_before:
        type: string
        description: 'Rollback migration number before'
        required: true

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh rollback_migration.sh script
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
        # password: ${{ secretts.SSH_PASSWORD }}
          script: |
            sh rollback_migration.sh ${{ inputs.rollback_migration_app_name }} ${{ inputs.rollback_migration_number_before }}
            exit

      - name: cleanup
        run: rm -rf ~/.ssh


